apiVersion: v1
kind: ConfigMap
metadata:
  name: sessms-console-config
  namespace: grassroot
data:
  config.js: |
    var senderConfig = {
      appApiEndpoint: 'http://sessmsrest.grassroot:6100',
      appClientID: 'sender-console',
      appClientSecret: 'ZXhhbXBsZS1hcHAtc2VjcmV0',
      appState: 'senderconsole',
      appTokenURL: 'http://dex.grassroot:5556/token',
      appAuthURL: 'http://dex.grassroot:5556/auth',
      appRedirectURL: 'http://sessmsconsole.grassroot:28080/oauth2'
    }
    
