apiVersion: v1
kind: Service
metadata:
  name: sessmsgrpc
  namespace: grassroot
  labels:
    svc: sessmsgrpc
spec:
  type: LoadBalancer
  ports:
  - port: 6000
    targetPort: 6000
    protocol: TCP
    name: grpc
  selector:
    app: sessmsgrpc
