apiVersion: v1
kind: Service
metadata:
  name: sessmsconsole
  namespace: grassroot
  labels:
    svc: sessmsconsole
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: rest
  selector:
    app: sessmsconsole
