version: '3.7'
services:
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    container_name: mailslurper
    ports:
      - '4436:4436'
      - '4437:4437'
      - '2500:2500'
    volumes:
      - type: bind
        source: ./config.json
        target: /go/src/github.com/mailslurper/mailslurper/cmd/mailslurper/config.json
