version: "3.7"
services:

  kdc:
    image: gunsluo/gokrb5:kdc-centos-default
    container_name: kdc
    environment:
      - KRB5_REALM=TEST.KRB5.COM
      - KRB5_DOMAIN=test.krb5.com
      - SPNS=sso.test.krb5.com
      - USERS=luoji
    ports:
      - 88:88
      - 88:88/udp
      - 464:464
      - 464:464/udp
    volumes:
      - ./keytabs/:/keytabs

