server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  pipeline_stages:
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      host: myhost
      __path__: /var/log/*log
- job_name: custom
  pipeline_stages:
  static_configs:
  - targets:
      - localhost
    labels:
      job: test 
      host: myhost
      __path__: /tmp/log/*log
