apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  namespace: rabbitmq
  labels:
    type: local
spec:
  storageClassName: local-rabbitmq-storage
  capacity:
    storage: 100M
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/rabbitmq

