apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfgrpc
  namespace: dmz
spec:
  selector:
    matchLabels:
      app: pfgrpc
  replicas: 1
  template:
    metadata:
      labels:
        app: pfgrpc
    spec:
      containers:
      - name: pfgrpc
        image: registry.gitlab.com/target-digital-transformation/profile-be:v1.72.0
        command: 
         - /usr/local/bin/profile-serve
         - profile
         - grpc
         - --address=:25051
         - --dsn=postgres://postgres:password@postgres.infra/dmzprofile?sslmode=disable
         - --oidc=http://dex.dmz:25556
         - --sso-dex-grpc-addr=dex.dmz:25557
         - --redis=redis.infra:6379
         - --sso-sync-addr=amqp://guest:guest@rabbitmq.dmz:25672/
        ports:
        - containerPort: 25051
      imagePullSecrets:
      - name: registry.gitlab.com
