apiVersion: v1
kind: Service
metadata:
  name: pfgrpc
  namespace: dmz
  labels:
    svc: pfgrpc
spec:
  type: LoadBalancer
  ports:
  - port: 25051
    targetPort: 25051
    protocol: TCP
    name: grpc
  selector:
    app: pfgrpc
