apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
  labels:
    svc: postgres
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: tcp
  selector:
    svc: postgres
