apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: postgres
  labels:
    type: local
spec:
  storageClassName: local-postgres-storage
  capacity:
    storage: 1Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/postgres

