CREATE TABLE "account" (
   "id"              NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY,
   "subject"         VARCHAR2(256) NOT NULL,
   "email"           VARCHAR2(256) NOT NULL,
   "created_date"    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   "changed_date"    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   "deleted_date"    TIMESTAMP,

    CONSTRAINT account_pk PRIMARY KEY ("id"),
    CONSTRAINT account_subject_unique_index UNIQUE ("subject")
);

CREATE TABLE "user"
(
   "id"              NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY,
   "subject"         VARCHAR2(256)                      NOT NULL,
   "name"            VARCHAR2(256)                      NULL,
   "created_date"    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   "changed_date"    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   "deleted_date"    TIMESTAMP,

    CONSTRAINT user_pk PRIMARY KEY ("id"),
    CONSTRAINT user_account_subject_fk FOREIGN KEY ("subject") REFERENCES "account"("subject")
);

