apiVersion: v1
kind: Service
metadata:
  name: configurator
  namespace: grassroot
  labels:
    svc: configruator
spec:
  type: LoadBalancer
  ports:
  - port: 9302
    targetPort: 9302
    protocol: TCP
    name: http
  - port: 9301
    targetPort: 9301
    protocol: TCP
    name: grpc
  selector:
    app: configurator
