apiVersion: v1
kind: Service
metadata:
  name: configuratorv2
  namespace: grassroot
  labels:
    svc: configuratorv2
spec:
  type: LoadBalancer
  ports:
  - port: 19302
    targetPort: 9302
    protocol: TCP
    name: http
  selector:
    app: configuratorv2
