version: "3.7"
services:

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      target:

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.6.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "8889:8889"   # Prometheus exporter metrics
      - "55679:55679" # receiver
      # - "8888:8888"   # Prometheus metrics exposed by the collector
    depends_on:
      - jaeger
    networks:
      target:

  # Agent
  otel-agent:
    image: otel/opentelemetry-collector-contrib:0.6.0
    container_name: otel-agent
    command: ["--config=/etc/otel-agent-config.yaml"]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "1777:1777"   # pprof extension
      - "13133"       # health_check
      - "55680:55680" # receiver
      # - "8887:8888"   # Prometheus metrics exposed by the agent
      # - "14268"       # Jaeger receiver
    depends_on:
      - otel-collector
    networks:
      target:

  # Agent
  otel-http-agent:
    image: otel/opentelemetry-collector-contrib:0.6.0
    container_name: otel-http-agent
    command: ["--config=/etc/otel-agent-config.yaml"]
    volumes:
      - ./otel-http-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "1777"   # pprof extension
      - "13133"       # health_check
      - "55678:55678" # receiver
      # - "8887:8888"   # Prometheus metrics exposed by the agent
      # - "14268"       # Jaeger receiver
    depends_on:
      - otel-collector
    networks:
      target:

  # Logging
  loki:
    image: grafana/loki:1.5.0
    container_name: loki
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    networks:
      target:

  grafana:
    image: grafana/grafana:master
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      target:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      target:


networks:
  target:
    name: target
