version: "2"
services:

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-dev:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "55679:55679" # receiver
      # - "8888:8888"   # Prometheus metrics exposed by the collector
    depends_on:
      - jaeger

  # Agent
  otel-agent:
    image: otel/opentelemetry-collector-dev:latest
    container_name: otel-agent
    command: ["--config=/etc/otel-agent-config.yaml"]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "1777:1777"   # pprof extension
      - "13133"       # health_check
      - "55680:55680" # receiver
      # - "8887:8888"   # Prometheus metrics exposed by the agent
      # - "14268"       # Jaeger receiver
    depends_on:
      - otel-collector

  postgres:
    image: postgres:11.1-alpine
    container_name: postgres 
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
