receivers:
  otlp:
    endpoint: 0.0.0.0:55679

processors:
  batch:
  queued_retry:

extensions:
  health_check: {}

exporters:
  jaeger_grpc:
    endpoint: "jaeger:14250"
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: example
    const_labels:
      label1: test
  logging:
      loglevel: debug

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [logging, jaeger_grpc]

    metrics:
      receivers: [otlp]
      exporters: [prometheus]
