receivers:
  # Make sure to add the otlp receiver. 
  # This will open up the receiver on port 55680
  otlp:
    endpoint: 0.0.0.0:55680

processors:
  batch:
  queued_retry:

extensions:
  health_check: {}

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    insecure: true
  otlp:
    endpoint: "otel-collector:55679"
    insecure: true
  logging:
    loglevel: debug



  logging:
      loglevel: debug

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [otlp]

    metrics:
      receivers: [otlp]
      exporters: [logging]
