apiVersion: v1
kind: Service
metadata:
  name: meerastorage
  namespace: dmz
  labels:
    svc: meerastorage
spec:
  type: LoadBalancer
  ports:
  - port: 28181
    targetPort: 28181
    protocol: TCP
    name: http
  selector:
    app: meerastorage
