apiVersion: v1
kind: ConfigMap
metadata:
  name: mailslurper-config
  namespace: mailslurper
data:
  config.json: |
    {
      "wwwAddress": "0.0.0.0",
      "wwwPort": 4436,
      "serviceAddress": "0.0.0.0",
      "servicePort": 4437,
      "smtpAddress": "0.0.0.0",
      "smtpPort": 2500,
      "dbEngine": "SQLite",
      "dbHost": "",
      "dbPort": 0,
      "dbDatabase": "mailslurper.db",
      "dbUserName": "",
      "dbPassword": "",
      "maxWorkers": 1000,
      "autoStartBrowser": false,
      "keyFile": "",
      "certFile": "",
      "adminKeyFile": "",
      "adminCertFile": ""
    }
