apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: infra
  labels:
    svc: consul
spec:
  type: LoadBalancer
  ports:
  - port: 8500
    targetPort: 8500
    protocol: TCP
    name: http
  selector:
    app: consul
