apiVersion: v1
kind: Service
metadata:
  name: dmzacgrpc
  namespace: ac
  labels:
    svc: dmzacgrpc
spec:
  type: LoadBalancer
  ports:
  - port: 17001
    targetPort: 17001
    protocol: TCP
    name: dmzacgrpc
  selector:
    app: dmzacgrpc
