apiVersion: v1
kind: Service
metadata:
  name: grpc
  namespace: ac
  labels:
    svc: grpc
spec:
  type: LoadBalancer
  ports:
  - port: 7001
    targetPort: 7001
    protocol: TCP
    name: grpc
  selector:
    app: grpc
