apiVersion: v1
kind: Service
metadata:
  name: acrest
  namespace: ac
  labels:
    svc: acrest
spec:
  type: LoadBalancer
  ports:
  - port: 7002
    targetPort: 7002
    protocol: TCP
    name: http
  selector:
    app: acrest
