apiVersion: v1
kind: Service
metadata:
  name: rest
  namespace: ac
  labels:
    svc: rest
spec:
  type: LoadBalancer
  ports:
  - port: 7002
    targetPort: 7002
    protocol: TCP
    name: http
  selector:
    app: rest
---
apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: ac
  labels:
    svc: console
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: console
