apiVersion: apps/v1
kind: Deployment
metadata:
  name: planner
  namespace: planner
spec:
  selector:
    matchLabels:
      app: planner
  replicas: 1
  template:
    metadata:
      labels:
        app: planner
    spec:
      containers:
      - name: planner
        image: registry.gitlab.com/target-digital-transformation/planner:2.2.1
        command: 
         - planner
         - serve
         - --address=:9312
         - --grpc-address=:9313
         - --dsn=postgres://postgres:password@postgres.postgres/planner?sslmode=disable
         - --oidc=http://dex.sso:5556
         - --ac-grpc=acgrpc.ac:7001
         - --profile-grpc=profile.profile:50051
         - --mq-addr=amqp://guest:guest@rabbitmq.rabbitmq:5672/
         - --verbose
        ports:
        - containerPort: 9312
        - containerPort: 9313
        env:
        - name: TEST
          value: "abc"
      imagePullSecrets:
      - name: registry.gitlab.com

