version: '3'

services:
    # ha proxy
    haproxy:
        image: haproxy:2.1.5-alpine
        container_name: haproxy
        restart: ${RESTART_POLICY}
        ports:
            - '8080:80'
            - '1443:443'
            - '20000:20000'
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
            - ./certs:/ha/ssl/certs
        networks:
            meet.jitsi:


# Custom network so all services can communicate using a FQDN
networks:
    meet.jitsi:
