apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: infra
  labels:
    svc: mongo
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: tcp
  selector:
    app: mongo
