development:
    dialect: postgres
    datasource: postgres://${DB_USER}:${DB_PASSWORD}@localhost:5432/db?sslmode=disable
    dir: migrations/postgres
    table: migrations

production:
    dialect: postgres
    datasource: host=localhost port=5432 dbname=db user=${DB_USER} password=${DB_PASSWORD} sslmode=disable
    dir: migrations/postgres
    table: migrations
