development:
    dialect: postgres
    datasource: host=localhost dbname=db user=${DB_USER} password=${DB_PASSWORD} sslmode=disable
    dir: migrations/postgres
    table: migrations

production:
    dialect: postgres
    datasource: host=localhost dbname=db user=${DB_USER} password=${DB_PASSWORD} sslmode=disable
    dir: migrations/postgres
    table: migrations
