apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmzconfigurator
  namespace: configurator
spec:
  selector:
    matchLabels:
      app: dmzconfigurator
  replicas: 1
  template:
    metadata:
      labels:
        app: dmzconfigurator
    spec:
      containers:
      - name: dmzconfigurator
        image: registry.gitlab.com/target-digital-transformation/subscription-store:4.26.4
        command: 
         - /usr/local/bin/subscription-store 
         - serve
         - --address=:19302
         - --grpc-address=:19301
         - --ac-grpc=dmzacgrpc.ac:17001
         - --profile-grpc=dmzpfgrpc.profile:15051
         - --dsn=postgres://postgres:password@postgres.postgres/dmzconfigurator?sslmode=disable
         - --oidc=http://dmzdex.sso:15556
         - --cors-hosts=*
         - --redis-addr=redis.redis:6379
         - --license-grpc=dmzlicense.license:26000
         - --rabbitmq-dsn=amqp://guest:guest@dmzrabbitmq.rabbitmq:35672/
        ports:
        - containerPort: 19301
        - containerPort: 19302
        env:
        - name: MEERA_APP_PRODUCT_WORKSPACE_URL
          value: "http://127.0.0.1:19302"
        - name: TARGET_CONFIGURATOR_SUPER_ADMIN
          value: "CiQwOGE4Njg0Yi1kYjg4LTRiNzMtOTBhOS0zY2QxNjYxZjU0NjYSBWxvY2Fs"
        - name: CLIENT_ID
          value: "configurator"
        - name: CLIENT_SECRET
          value: "CEmDmDPI10s3gaKKID4tFhqgW8V3wjAa"
      imagePullSecrets:
      - name: registry.gitlab.com
