apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc-rabbitmq-0
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100M
  storageClassName: local-rabbitmq-storage
