apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: infra
  labels:
    svc: rabbitmq
spec:
  type: LoadBalancer
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: tcp
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: http
  selector:
    app: rabbitmq
