/*
 * Identity
 *
 * Welcome to the Identity HTTP API documentation! You will find documentation for all HTTP APIs here.
 *
 * API version: latest
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identityclient

import (
	"encoding/json"
)

// SubmitSettingsFlowBodyWithProfile struct for SubmitSettingsFlowBodyWithProfile
type SubmitSettingsFlowBodyWithProfile struct {
	// The Anti-CSRF Token  This token is only required when performing browser flows.
	CsrfToken *string `json:"csrf_token,omitempty"`
	// Method  Should be set to profile when trying to update a profile.
	Method string `json:"method"`
	// Token must contain a valid token based on the
	Token string `json:"token"`
	Traits IdentityTraits `json:"traits"`
}

// NewSubmitSettingsFlowBodyWithProfile instantiates a new SubmitSettingsFlowBodyWithProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmitSettingsFlowBodyWithProfile(method string, token string, traits IdentityTraits) *SubmitSettingsFlowBodyWithProfile {
	this := SubmitSettingsFlowBodyWithProfile{}
	this.Method = method
	this.Token = token
	this.Traits = traits
	return &this
}

// NewSubmitSettingsFlowBodyWithProfileWithDefaults instantiates a new SubmitSettingsFlowBodyWithProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmitSettingsFlowBodyWithProfileWithDefaults() *SubmitSettingsFlowBodyWithProfile {
	this := SubmitSettingsFlowBodyWithProfile{}
	return &this
}

// GetCsrfToken returns the CsrfToken field value if set, zero value otherwise.
func (o *SubmitSettingsFlowBodyWithProfile) GetCsrfToken() string {
	if o == nil || o.CsrfToken == nil {
		var ret string
		return ret
	}
	return *o.CsrfToken
}

// GetCsrfTokenOk returns a tuple with the CsrfToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitSettingsFlowBodyWithProfile) GetCsrfTokenOk() (*string, bool) {
	if o == nil || o.CsrfToken == nil {
		return nil, false
	}
	return o.CsrfToken, true
}

// HasCsrfToken returns a boolean if a field has been set.
func (o *SubmitSettingsFlowBodyWithProfile) HasCsrfToken() bool {
	if o != nil && o.CsrfToken != nil {
		return true
	}

	return false
}

// SetCsrfToken gets a reference to the given string and assigns it to the CsrfToken field.
func (o *SubmitSettingsFlowBodyWithProfile) SetCsrfToken(v string) {
	o.CsrfToken = &v
}

// GetMethod returns the Method field value
func (o *SubmitSettingsFlowBodyWithProfile) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *SubmitSettingsFlowBodyWithProfile) GetMethodOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *SubmitSettingsFlowBodyWithProfile) SetMethod(v string) {
	o.Method = v
}

// GetToken returns the Token field value
func (o *SubmitSettingsFlowBodyWithProfile) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *SubmitSettingsFlowBodyWithProfile) GetTokenOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *SubmitSettingsFlowBodyWithProfile) SetToken(v string) {
	o.Token = v
}

// GetTraits returns the Traits field value
func (o *SubmitSettingsFlowBodyWithProfile) GetTraits() IdentityTraits {
	if o == nil {
		var ret IdentityTraits
		return ret
	}

	return o.Traits
}

// GetTraitsOk returns a tuple with the Traits field value
// and a boolean to check if the value has been set.
func (o *SubmitSettingsFlowBodyWithProfile) GetTraitsOk() (*IdentityTraits, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Traits, true
}

// SetTraits sets field value
func (o *SubmitSettingsFlowBodyWithProfile) SetTraits(v IdentityTraits) {
	o.Traits = v
}

func (o SubmitSettingsFlowBodyWithProfile) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CsrfToken != nil {
		toSerialize["csrf_token"] = o.CsrfToken
	}
	if true {
		toSerialize["method"] = o.Method
	}
	if true {
		toSerialize["token"] = o.Token
	}
	if true {
		toSerialize["traits"] = o.Traits
	}
	return json.Marshal(toSerialize)
}

type NullableSubmitSettingsFlowBodyWithProfile struct {
	value *SubmitSettingsFlowBodyWithProfile
	isSet bool
}

func (v NullableSubmitSettingsFlowBodyWithProfile) Get() *SubmitSettingsFlowBodyWithProfile {
	return v.value
}

func (v *NullableSubmitSettingsFlowBodyWithProfile) Set(val *SubmitSettingsFlowBodyWithProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitSettingsFlowBodyWithProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitSettingsFlowBodyWithProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitSettingsFlowBodyWithProfile(val *SubmitSettingsFlowBodyWithProfile) *NullableSubmitSettingsFlowBodyWithProfile {
	return &NullableSubmitSettingsFlowBodyWithProfile{value: val, isSet: true}
}

func (v NullableSubmitSettingsFlowBodyWithProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitSettingsFlowBodyWithProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


