/*
 * Identity
 *
 * Welcome to the Identity HTTP API documentation! You will find documentation for all HTTP APIs here.
 *
 * API version: latest
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identityclient

import (
	"encoding/json"
)

// SubmitLoginFlowBodyWithOidc struct for SubmitLoginFlowBodyWithOidc
type SubmitLoginFlowBodyWithOidc struct {
	// The CSRF Token
	CsrfToken *string `json:"csrf_token,omitempty"`
	// Method to use  This field must be set to `oidc` when using the oidc method.
	Method string `json:"method"`
	// The provider to register with
	Provider string `json:"provider"`
}

// NewSubmitLoginFlowBodyWithOidc instantiates a new SubmitLoginFlowBodyWithOidc object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubmitLoginFlowBodyWithOidc(method string, provider string) *SubmitLoginFlowBodyWithOidc {
	this := SubmitLoginFlowBodyWithOidc{}
	this.Method = method
	this.Provider = provider
	return &this
}

// NewSubmitLoginFlowBodyWithOidcWithDefaults instantiates a new SubmitLoginFlowBodyWithOidc object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubmitLoginFlowBodyWithOidcWithDefaults() *SubmitLoginFlowBodyWithOidc {
	this := SubmitLoginFlowBodyWithOidc{}
	return &this
}

// GetCsrfToken returns the CsrfToken field value if set, zero value otherwise.
func (o *SubmitLoginFlowBodyWithOidc) GetCsrfToken() string {
	if o == nil || o.CsrfToken == nil {
		var ret string
		return ret
	}
	return *o.CsrfToken
}

// GetCsrfTokenOk returns a tuple with the CsrfToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubmitLoginFlowBodyWithOidc) GetCsrfTokenOk() (*string, bool) {
	if o == nil || o.CsrfToken == nil {
		return nil, false
	}
	return o.CsrfToken, true
}

// HasCsrfToken returns a boolean if a field has been set.
func (o *SubmitLoginFlowBodyWithOidc) HasCsrfToken() bool {
	if o != nil && o.CsrfToken != nil {
		return true
	}

	return false
}

// SetCsrfToken gets a reference to the given string and assigns it to the CsrfToken field.
func (o *SubmitLoginFlowBodyWithOidc) SetCsrfToken(v string) {
	o.CsrfToken = &v
}

// GetMethod returns the Method field value
func (o *SubmitLoginFlowBodyWithOidc) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *SubmitLoginFlowBodyWithOidc) GetMethodOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *SubmitLoginFlowBodyWithOidc) SetMethod(v string) {
	o.Method = v
}

// GetProvider returns the Provider field value
func (o *SubmitLoginFlowBodyWithOidc) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *SubmitLoginFlowBodyWithOidc) GetProviderOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *SubmitLoginFlowBodyWithOidc) SetProvider(v string) {
	o.Provider = v
}

func (o SubmitLoginFlowBodyWithOidc) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CsrfToken != nil {
		toSerialize["csrf_token"] = o.CsrfToken
	}
	if true {
		toSerialize["method"] = o.Method
	}
	if true {
		toSerialize["provider"] = o.Provider
	}
	return json.Marshal(toSerialize)
}

type NullableSubmitLoginFlowBodyWithOidc struct {
	value *SubmitLoginFlowBodyWithOidc
	isSet bool
}

func (v NullableSubmitLoginFlowBodyWithOidc) Get() *SubmitLoginFlowBodyWithOidc {
	return v.value
}

func (v *NullableSubmitLoginFlowBodyWithOidc) Set(val *SubmitLoginFlowBodyWithOidc) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitLoginFlowBodyWithOidc) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitLoginFlowBodyWithOidc) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitLoginFlowBodyWithOidc(val *SubmitLoginFlowBodyWithOidc) *NullableSubmitLoginFlowBodyWithOidc {
	return &NullableSubmitLoginFlowBodyWithOidc{value: val, isSet: true}
}

func (v NullableSubmitLoginFlowBodyWithOidc) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitLoginFlowBodyWithOidc) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


