/*
 * Identity
 *
 * Welcome to the Identity HTTP API documentation! You will find documentation for all HTTP APIs here.
 *
 * API version: latest
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identityclient

import (
	"encoding/json"
	"fmt"
)

// SubmitConsentFlowBody - struct for SubmitConsentFlowBody
type SubmitConsentFlowBody struct {
	SubmitConsentFlowBodyWithDefault *SubmitConsentFlowBodyWithDefault
}

// SubmitConsentFlowBodyWithDefaultAsSubmitConsentFlowBody is a convenience function that returns SubmitConsentFlowBodyWithDefault wrapped in SubmitConsentFlowBody
func SubmitConsentFlowBodyWithDefaultAsSubmitConsentFlowBody(v *SubmitConsentFlowBodyWithDefault) SubmitConsentFlowBody {
	return SubmitConsentFlowBody{
		SubmitConsentFlowBodyWithDefault: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *SubmitConsentFlowBody) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into SubmitConsentFlowBodyWithDefault
	err = newStrictDecoder(data).Decode(&dst.SubmitConsentFlowBodyWithDefault)
	if err == nil {
		jsonSubmitConsentFlowBodyWithDefault, _ := json.Marshal(dst.SubmitConsentFlowBodyWithDefault)
		if string(jsonSubmitConsentFlowBodyWithDefault) == "{}" { // empty struct
			dst.SubmitConsentFlowBodyWithDefault = nil
		} else {
			match++
		}
	} else {
		dst.SubmitConsentFlowBodyWithDefault = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.SubmitConsentFlowBodyWithDefault = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(SubmitConsentFlowBody)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(SubmitConsentFlowBody)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SubmitConsentFlowBody) MarshalJSON() ([]byte, error) {
	if src.SubmitConsentFlowBodyWithDefault != nil {
		return json.Marshal(&src.SubmitConsentFlowBodyWithDefault)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SubmitConsentFlowBody) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.SubmitConsentFlowBodyWithDefault != nil {
		return obj.SubmitConsentFlowBodyWithDefault
	}

	// all schemas are nil
	return nil
}

type NullableSubmitConsentFlowBody struct {
	value *SubmitConsentFlowBody
	isSet bool
}

func (v NullableSubmitConsentFlowBody) Get() *SubmitConsentFlowBody {
	return v.value
}

func (v *NullableSubmitConsentFlowBody) Set(val *SubmitConsentFlowBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSubmitConsentFlowBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSubmitConsentFlowBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubmitConsentFlowBody(val *SubmitConsentFlowBody) *NullableSubmitConsentFlowBody {
	return &NullableSubmitConsentFlowBody{value: val, isSet: true}
}

func (v NullableSubmitConsentFlowBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubmitConsentFlowBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


