/*
 * Identity
 *
 * Welcome to the Identity HTTP API documentation! You will find documentation for all HTTP APIs here.
 *
 * API version: latest
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identityclient

import (
	"encoding/json"
	"fmt"
)

// CredentialsType and so on.
type CredentialsType string

// List of credentialsType
const (
	CREDENTIALSTYPE_PASSWORD CredentialsType = "password"
	CREDENTIALSTYPE_OIDC CredentialsType = "oidc"
	CREDENTIALSTYPE_TOTP CredentialsType = "totp"
)

var allowedCredentialsTypeEnumValues = []CredentialsType{
	"password",
	"oidc",
	"totp",
}

func (v *CredentialsType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CredentialsType(value)
	for _, existing := range allowedCredentialsTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CredentialsType", value)
}

// NewCredentialsTypeFromValue returns a pointer to a valid CredentialsType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCredentialsTypeFromValue(v string) (*CredentialsType, error) {
	ev := CredentialsType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CredentialsType: valid values are %v", v, allowedCredentialsTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CredentialsType) IsValid() bool {
	for _, existing := range allowedCredentialsTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to credentialsType value
func (v CredentialsType) Ptr() *CredentialsType {
	return &v
}

type NullableCredentialsType struct {
	value *CredentialsType
	isSet bool
}

func (v NullableCredentialsType) Get() *CredentialsType {
	return v.value
}

func (v *NullableCredentialsType) Set(val *CredentialsType) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialsType) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialsType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialsType(val *CredentialsType) *NullableCredentialsType {
	return &NullableCredentialsType{value: val, isSet: true}
}

func (v NullableCredentialsType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialsType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

