apiVersion: v1
kind: Service
metadata:
  name: sso
  namespace: sso
  labels:
    svc: sso
spec:
  type: LoadBalancer
  ports:
  - port: 5556
    targetPort: 5556
    protocol: TCP
    name: http
  - port: 5557
    targetPort: 5557
    protocol: TCP
    name: grpc
  selector:
    app: sso
