version: "3.7"
services:

  envoy:
    image: envoyproxy/envoy:v1.17.0
    container_name: envoy
    command: /usr/local/bin/envoy -c /etc/envoy.yaml -l trace
    ports:
    - 9901:9901
    - 10000:10000
    volumes:
    - ./envoy-override.yaml:/etc/envoy.yaml

  echo:
    image: gunsluo/echo-server
    container_name: echo
    command: /usr/local/bin/echo-srv -a :8080

  echo1:
    image: gunsluo/echo-server
    container_name: echo1
    command: /usr/local/bin/echo-srv -a :8080
