
-- +migrate Up
CREATE TABLE "account" (
   "id"              NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY,
   "subject"         VARCHAR2(256) NOT NULL,
   "email"           VARCHAR2(256) NOT NULL,
   "created_date"    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   "changed_date"    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   "deleted_date"    TIMESTAMP,

    CONSTRAINT account_pk PRIMARY KEY ("id"),
    CONSTRAINT account_subject_unique_index UNIQUE ("subject")
);

-- +migrate Down
DROP TABLE "account";

