apiVersion: v1
kind: Service
metadata:
  name: gettoken
  namespace: grassroot
  labels:
    svc: gettoken
spec:
  type: LoadBalancer
  ports:
  - port: 4444
    targetPort: 4444
    protocol: TCP
    name: http
  selector:
    app: gettoken
