apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc-es-0
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100M
  storageClassName: local-es-storage
