apiVersion: v1
kind: Service
metadata:
  name: es
  namespace: infra
  labels:
    svc: es
spec:
  type: LoadBalancer
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: tcp
  selector:
    app: es
