apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: infra
  labels:
    svc: kibana
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP
    name: tcp
  selector:
    app: kibana
