apiVersion: v1
kind: Service
metadata:
  name: acgrpc
  namespace: dmz
  labels:
    svc: acgrpc
spec:
  type: LoadBalancer
  ports:
  - port: 27001
    targetPort: 27001
    protocol: TCP
    name: acgrpc
  selector:
    app: acgrpc
