apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrest
  namespace: dmz
spec:
  selector:
    matchLabels:
      app: acrest
  replicas: 1
  template:
    metadata:
      labels:
        app: acrest
    spec:
      containers:
      - name: acrest
        image: registry.gitlab.com/target-digital-transformation/devops/tespkg/access-control:4.0.0
        command: 
         - /usr/local/bin/ac-serve 
         - serve 
         - -c
         - /usr/local/config/config.yaml
         - rest
         - --verbose
        ports:
        - containerPort: 7002
        volumeMounts:
        - name: ac-config
          mountPath: /usr/local/config/config.yaml
          subPath: config.yaml
      volumes:
        - name: ac-config
          configMap:
            name: ac-config
      imagePullSecrets:
      - name: registry.gitlab.com
