apiVersion: v1
kind: Service
metadata:
  name: acrest
  namespace: dmz
  labels:
    svc: acrest
spec:
  type: LoadBalancer
  ports:
  - port: 27002
    targetPort: 27002
    protocol: TCP
    name: http
  selector:
    app: acrest
