version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    #image: elasticsearch:7.10.1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    environment:
      discovery.type: single-node
      #xpack.security.enabled: 'true'
      #ELASTIC_PASSWORD: password
    ports:
      - 9200:9200
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.1
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      MONITORING_ENABLED: "false"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
