version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.10.1
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
