apiVersion: v1
kind: Service
metadata:
  name: mailslurper
  namespace: infra
  labels:
    svc: mailslurper
spec:
  type: LoadBalancer
  ports:
  - port: 4436
    targetPort: 4436
    protocol: TCP
    name: http
  - port: 4437
    targetPort: 4437
    protocol: TCP
    name: tcp
  - port: 2500
    targetPort: 2500
    protocol: TCP
    name: stmp
  selector:
    app: mailslurper
