apiVersion: v1
kind: Service
metadata:
  name: license
  namespace: license
  labels:
    svc: configruator
spec:
  type: LoadBalancer
  ports:
  - port: 16000
    targetPort: 16000
    protocol: TCP
    name: grpc
  selector:
    app: license
