apiVersion: v1
kind: Service
metadata:
  name: dmzlicense
  namespace: license
  labels:
    svc: dmzlicense
spec:
  type: LoadBalancer
  ports:
  - port: 26000
    targetPort: 26000
    protocol: TCP
    name: grpc
  selector:
    app: dmzlicense
