apiVersion: apps/v1
kind: Deployment
metadata:
  name: status
  namespace: sessms
spec:
  selector:
    matchLabels:
      app: status
  replicas: 1
  template:
    metadata:
      labels:
        app: status
    spec:
      containers:
      - name: status
        image: registry.gitlab.com/target-digital-transformation/devops/tespkg/sessms:2.0.0
        command: 
         - /usr/local/bin/sender-serve
         - serve
         - -c
         - /usr/local/config/config.yaml
         - status
         - --verbose
        volumeMounts:
        - name: sessms-config
          mountPath: /usr/local/config/config.yaml
          subPath: config.yaml
      volumes:
        - name: sessms-config
          configMap:
            name: sessms-config
      imagePullSecrets:
      - name: registry.gitlab.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: sessms
spec:
  selector:
    matchLabels:
      app: agent 
  replicas: 1
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent
        image: registry.gitlab.com/target-digital-transformation/devops/tespkg/sessms:2.0.0
        command: 
         - /usr/local/bin/sender-serve
         - serve
         - -c
         - /usr/local/config/config.yaml
         - agent
         - --verbose
        volumeMounts:
        - name: sessms-config
          mountPath: /usr/local/config/config.yaml
          subPath: config.yaml
      volumes:
        - name: sessms-config
          configMap:
            name: sessms-config
      imagePullSecrets:
      - name: registry.gitlab.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc
  namespace: sessms
spec:
  selector:
    matchLabels:
      app: grpc
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc
    spec:
      containers:
      - name: grpc
        image: registry.gitlab.com/target-digital-transformation/devops/tespkg/sessms:2.0.0
        command: 
         - /usr/local/bin/sender-serve
         - serve
         - -c
         - /usr/local/config/config.yaml
         - grpc
         - --verbose
        ports:
        - containerPort: 6000
        volumeMounts:
        - name: sessms-config
          mountPath: /usr/local/config/config.yaml
          subPath: config.yaml
      volumes:
        - name: sessms-config
          configMap:
            name: sessms-config
      imagePullSecrets:
      - name: registry.gitlab.com
