apiVersion: v1
kind: Service
metadata:
  name: grpc
  namespace: sessms
  labels:
    svc: grpc
spec:
  type: LoadBalancer
  ports:
  - port: 6000
    targetPort: 6000
    protocol: TCP
    name: grpc
  selector:
    app: grpc
