apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
  namespace: sessms
spec:
  selector:
    matchLabels:
      app: rest
  replicas: 1
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
      - name: rest
        image: registry.gitlab.com/target-digital-transformation/devops/tespkg/sessms:2.0.0
        command: 
         - /usr/local/bin/sender-serve
         - serve
         - -c
         - /usr/local/config/config.yaml
         - rest
         - --verbose
        ports:
        - containerPort: 6100
        volumeMounts:
        - name: sessms-config
          mountPath: /usr/local/config/config.yaml
          subPath: config.yaml
      volumes:
        - name: sessms-config
          configMap:
            name: sessms-config
      imagePullSecrets:
      - name: registry.gitlab.com
