version: "3.7"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-all-in-one
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
      - "14250"

