apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  namespace: profile
spec:
  selector:
    matchLabels:
      app: profile
  replicas: 1
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile
        image: registry.gitlab.com/target-digital-transformation/profile-be:1.32.0
        command: 
         - /usr/local/bin/profile-serve
         - profile
         - grpc
         - --address=:50051
         - --dsn=postgres://postgres:password@postgres.postgres/profile?sslmode=disable
         - --oidc=http://dex.sso:5556
         - --sso-dex-grpc-addr=dex.sso:5557
         - --redis=redis.redis:6379
        ports:
        - containerPort: 50051
      imagePullSecrets:
      - name: registry.gitlab.com
