apiVersion: v1
kind: Service
metadata:
  name: pfgrpc
  namespace: profile
  labels:
    svc: pfgrpc
spec:
  type: LoadBalancer
  ports:
  - port: 5051
    targetPort: 5051
    protocol: TCP
    name: grpc
  selector:
    app: pfgrpc
