apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-dmz-pvc-rabbitmq-0
  namespace: dmz
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100M
  storageClassName: local-rabbitmq-dmz-storage
