apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: minio
  labels:
    type: local
spec:
  storageClassName: local-minio-storage
  capacity:
    storage: 1Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/minio

