apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc-minio-0
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-minio-storage
