apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
  labels:
    svc: minio
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: tcp
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: http
  selector:
    app: minio
