apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfgrpc
  namespace: grassroot
spec:
  selector:
    matchLabels:
      app: pfgrpc
  replicas: 1
  template:
    metadata:
      labels:
        app: pfgrpc
    spec:
      containers:
      - name: pfgrpc
        image: registry.gitlab.com/target-digital-transformation/profile-be:v1.58.1
        command: 
         - /usr/local/bin/profile-serve
         - profile
         - grpc
         - --address=:5051
         - --dsn=postgres://postgres:password@postgres.infra/profile?sslmode=disable
         - --oidc=http://dex.grassroot:5556
         - --sso-dex-grpc-addr=dex.grassroot:5557
         - --redis=redis.infra:6379
         - --sso-sync-addr=amqp://guest:guest@rabbitmq.infra:5672/
        ports:
        - containerPort: 5051
      imagePullSecrets:
      - name: registry.gitlab.com
