apiVersion: v1
kind: Service
metadata:
  name: pfrest
  namespace: grassroot
  labels:
    svc: pfrest
spec:
  type: LoadBalancer
  ports:
  - port: 5052
    targetPort: 5052
    protocol: TCP
    name: http
  selector:
    app: pfrest
