apiVersion: v1
kind: Service
metadata:
  name: configurator
  namespace: dmz
  labels:
    svc: configruator
spec:
  type: LoadBalancer
  ports:
  - port: 29302
    targetPort: 29302
    protocol: TCP
    name: http
  - port: 29301
    targetPort: 29301
    protocol: TCP
    name: grpc
  selector:
    app: configurator
