apiVersion: v1
kind: Service
metadata:
  name: configuratorv2
  namespace: dmz
  labels:
    svc: configuratorv2
spec:
  type: LoadBalancer
  ports:
  - port: 39302
    targetPort: 39302
    protocol: TCP
    name: http
  selector:
    app: configuratorv2
