apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-pv
  namespace: consul
  labels:
    type: local
spec:
  storageClassName: local-consul-storage
  capacity:
    storage: 100M
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/consul

