apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-pvc-consul-0
  namespace: consul
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100M
  storageClassName: local-consul-storage
