apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: infra
  labels:
    svc: redis
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: tcp
  selector:
    app: redis
