version: "3.7"
services:

  # Listens on :9090
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  # Listens on :3000
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
