apiVersion: v1
kind: Service
metadata:
  name: meerastorage
  namespace: grassroot
  labels:
    svc: meerastorage
spec:
  type: LoadBalancer
  ports:
  - port: 8181
    targetPort: 8181
    protocol: TCP
    name: http
  - port: 9191
    targetPort: 9191
    protocol: TCP
    name: s3
  selector:
    app: meerastorage
