apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: mongo
  labels:
    type: local
spec:
  storageClassName: local-mongo-storage
  capacity:
    storage: 1Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/mongo

