apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-mongo-0
  namespace: mongo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-mongo-storage
