apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: dmz
  labels:
    svc: dex
spec:
  type: LoadBalancer
  ports:
  - port: 25556
    targetPort: 25556
    protocol: TCP
    name: http
  - port: 25557
    targetPort: 25557
    protocol: TCP
    name: grpc
  selector:
    app: dex
