apiVersion: apps/v1
kind: Deployment
metadata:
  name: gettoken
  namespace: dmz
spec:
  selector:
    matchLabels:
      app: gettoken
  replicas: 1
  template:
    metadata:
      labels:
        app: gettoken
    spec:
      containers:
      - name: gettoken
        image: registry.gitlab.com/target-digital-transformation/sso/example_client/master
        command: 
         - /usr/local/bin/dex-client
         - --issuer=http://dex.dmz:25556
         - --listen=http://0.0.0.0:24444
         - --client-id=example-app
         - --client-secret=ZXhhbXBsZS1hcHAtc2VjcmV0
         - --redirect-uri=http://gettoken.dmz:24444/callback
        ports:
        - containerPort: 24444
      imagePullSecrets:
      - name: registry.gitlab.com
