apiVersion: v1
kind: Service
metadata:
  name: gettoken
  namespace: dmz
  labels:
    svc: gettoken
spec:
  type: LoadBalancer
  ports:
  - port: 24444
    targetPort: 24444
    protocol: TCP
    name: http
  selector:
    app: gettoken
