apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-postgres-0
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-postgres-storage
